### ISSUE TITLE
How can I cache where statment?

### ISSUE THREAD

**Issue by davidsoderberg** [mikenolimits/cache-repository#1]
How can I cache where statment?

**Comment by kantorcodes** [comment]
Hi David,

`$this->whereCached('my_key',$key);`

That's quite simple! I'll add it to the docs too. 

Now, if you want to cache multiple arguments/ specific queries:

`$this->whereCached(['myFirstKey','mySecondKey'], [$myFirstKey,$mySecondKey])`

Now if you want to get specific and use other conditions:

`$this->whereCached(['myFirstKey','mySecondKey'], [$myFirstKey,$mySecondKey],['=','LIKE'])`

Or maybe even more specific: 

`$this->whereCached(['myFirstKey','mySecondKey'], [$myFirstKey,$mySecondKey],['=','LIKE'],['OR','OR'])`

Also note, you can set the cache lifetime before any query by calling `setCacheLifetime($myNumberInMinutes)`
